jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9

cache:
  directories:
  - $HOME/.m2

matrix:
  include:
    - jdk: openjdk10
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
  - cd ./Project FinalFantasy/
language: ruby
rvm:
  - 2.0.0
install:
- gem install "rubygems-update:<3.0.0" --no-document
- update_rubygems


